### ISSUE TITLE
ModuleNotFoundError: No module named 'strings'

### ISSUE THREAD

**Issue by blackwinggoat** [epinna/weevely3#107]
(base) 172-126-0-154:weevely3 user$ sudo python3 weevely.py 
Traceback (most recent call last):
  File "weevely.py", line 2, in <module>
    from core.terminal import Terminal
  File "/Users/user/weevely3/core/terminal.py", line 6, in <module>
    from core.module import Status
  File "/Users/user/weevely3/core/module.py", line 14, in <module>
    from core.vectorlist import VectorList
  File "/Users/user/weevely3/core/vectorlist.py", line 15, in <module>
    from core.vectors import Os
  File "/Users/user/weevely3/core/vectors.py", line 16, in <module>
    import utils
  File "/Users/user/weevely3/utils/__init__.py", line 3, in <module>
    import strings
ModuleNotFoundError: No module named 'strings'

**Comment by epinna** [comment]
It only supports Python 2.x.
