### ISSUE TITLE
AttributeError: 'module' object has no attribute 'create_default_context'

### ISSUE THREAD

**Issue by blackwinggoat** [epinna/weevely3#108]
weevely> ls
Traceback (most recent call last):
  File "./weevely.py", line 99, in <module>
    main(arguments)
  File "./weevely.py", line 52, in main
    Terminal(session).cmdloop()
  File "/Users/user/anaconda3/lib/python2.7/cmd.py", line 141, in cmdloop
    line = self.precmd(line)
  File "/Users/user/weevely3/core/terminal.py", line 196, in precmd
    self.session['shell_sh']['status'] = modules.loaded['shell_sh'].setup()
  File "/Users/user/weevely3/modules/shell/sh.py", line 99, in setup
    condition = lambda result: (
  File "/Users/user/weevely3/core/vectorlist.py", line 80, in find_first_result
    result = vector.run(format_args)
  File "/Users/user/weevely3/core/vectors.py", line 121, in run
    result = modules.loaded[self.module].run_argv(formatted)
  File "/Users/user/weevely3/core/module.py", line 173, in run_argv
    self.session[self.name]['status'] = self.setup()
  File "/Users/user/weevely3/modules/shell/php.py", line 67, in setup
    status = self._check_interpreter(channel)
  File "/Users/user/weevely3/modules/shell/php.py", line 39, in _check_interpreter
    response, code, error = channel.send(command)
  File "/Users/user/weevely3/core/channels/channel.py", line 111, in send
    self._additional_handlers()
  File "/Users/user/weevely3/core/channels/channel.py", line 92, in _additional_handlers
    ctx = ssl.create_default_context()
AttributeError: 'module' object has no attribute 'create_default_context'
![Screen Shot 2019-05-12 at 10 54 03](https://user-images.githubusercontent.com/46078819/57577199-5588d480-74a4-11e9-81e0-93e27b6f639c.png)

**Comment by epinna** [comment]
You're using an old python version. Update your python version, see issue #60 .
