### ISSUE TITLE
Issue running Weevely

### ISSUE THREAD

**Issue by SkeltonMod** [epinna/weevely3#111]
When I run weevely with "python2 weevely.py"
I get the following error
`Traceback (most recent call last):
  File "weevely.py", line 2, in <module>
    from core.terminal import Terminal
  File "/home/gvim/weevely3/core/terminal.py", line 6, in <module>
    from core.module import Status
  File "/home/gvim/weevely3/core/module.py", line 14, in <module>
    from core.vectorlist import VectorList
  File "/home/gvim/weevely3/core/vectorlist.py", line 15, in <module>
    from core.vectors import Os
  File "/home/gvim/weevely3/core/vectors.py", line 11, in <module>
    from mako.template import Template
ImportError: No module named mako.template
`
Any Idea on where I messed up? I got the requirements installed already.

**Comment by epinna** [comment]
There is some error on the `mako` module on your box, I can't help much. Did you solve this?

**Comment by SkeltonMod** [comment]
Yes, technically not a fix but using kali instead of arch worked fine for me
