### ISSUE TITLE
setting add_random_param_nocache to True causes AttributeError

### ISSUE THREAD

**Issue by JapaneseText** [epinna/weevely3#135]
Hey, I was reading issue #8 , and after setting add_random_param_nocache to true, i got an AttributeError.

Here's the full error:

weevely> help
Traceback (most recent call last):
  File "./weevely.py", line 104, in <module>
    main(arguments)
  File "./weevely.py", line 57, in main
    Terminal(session).cmdloop()
  File "/usr/lib/python3.8/cmd.py", line 137, in cmdloop
    line = self.precmd(line)
  File "/home/fricking_weeb/Desktop/weevely3-master/core/terminal.py", line 207, in precmd
    self.session['shell_sh']['status'] = modules.loaded['shell_sh'].setup()
  File "/home/fricking_weeb/Desktop/weevely3-master/modules/shell/sh.py", line 96, in setup
    result) = self.vectors.find_first_result(
  File "/home/fricking_weeb/Desktop/weevely3-master/core/vectorlist.py", line 80, in find_first_result
    result = vector.run(format_args)
  File "/home/fricking_weeb/Desktop/weevely3-master/core/vectors.py", line 121, in run
    result = modules.loaded[self.module].run_argv(formatted)
  File "/home/fricking_weeb/Desktop/weevely3-master/core/module.py", line 173, in run_argv
    self.session[self.name]['status'] = self.setup()
  File "/home/fricking_weeb/Desktop/weevely3-master/modules/shell/php.py", line 67, in setup
    status = self._check_interpreter(channel)
  File "/home/fricking_weeb/Desktop/weevely3-master/modules/shell/php.py", line 39, in _check_interpreter
    response, code, error = channel.send(command)
  File "/home/fricking_weeb/Desktop/weevely3-master/core/channels/channel.py", line 109, in send
    response = self.channel_loaded.send(
  File "/home/fricking_weeb/Desktop/weevely3-master/core/channels/obfpost/obfpost.py", line 86, in send
    else utils.http.add_random_url_param(self.url)
  File "/home/fricking_weeb/Desktop/weevely3-master/utils/http.py", line 34, in add_random_url_param
    charset = string.letters
AttributeError: module 'string' has no attribute 'letters'

(this is when connecting to the backdoor)

**Comment by JapaneseText** [comment]
Doesn't seem like there's any related errors i could find on google

**Comment by JapaneseText** [comment]
Enabling debug mode doesn't really help either

**Comment by epinna** [comment]
Fixed, thanks.
