### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by Nicals** [epinna/weevely3#15]
I've juste triggered an encoding error inside the sql_console module. Didn't have the time to check further in, but here is the error message I received and the .

```
[D][module] Traceback (most recent call last):
  File "/home/nico/exp/tools/shells/weevely3/core/module.py", line 105, in run_cmdline
    result = self.run_argv(command)
  File "/home/nico/exp/tools/shells/weevely3/core/module.py", line 178, in run_argv
    return self.run()
  File "/home/nico/exp/tools/shells/weevely3/modules/sql/console.py", line 121, in run
    self.print_result(result)
  File "/home/nico/exp/tools/shells/weevely3/modules/sql/console.py", line 129, in print_result
    Module.print_result(self, result['result'])
  File "/home/nico/exp/tools/shells/weevely3/core/module.py", line 348, in print_result
    log.info(utils.prettify.tablify(result))
  File "/home/nico/exp/tools/shells/weevely3/utils/prettify.py", line 56, in tablify
    output = table.get_string()
  File "/home/nico/.virtualenvs/weevely/local/lib/python2.7/site-packages/prettytable.py", line 987, in get_string
    formatted_rows = self._format_rows(rows, options)
  File "/home/nico/.virtualenvs/weevely/local/lib/python2.7/site-packages/prettytable.py", line 942, in _format_rows
    return [self._format_row(row, options) for row in rows]
  File "/home/nico/.virtualenvs/weevely/local/lib/python2.7/site-packages/prettytable.py", line 939, in _format_row
    return [self._format_value(field, value) for (field, value) in zip(self._field_names, row)]
  File "/home/nico/.virtualenvs/weevely/local/lib/python2.7/site-packages/prettytable.py", line 890, in _format_value
    return self._unicode(value)
  File "/home/nico/.virtualenvs/weevely/local/lib/python2.7/site-packages/prettytable.py", line 181, in _unicode
    value = unicode(value, self.encoding, "strict")
  File "/home/nico/.virtualenvs/weevely/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 4: invalid continuation byte

```

**Comment by epinna** [comment]
The fix with -encoding makes sense and gives a proper flexibility to the user, thanks. I've planned to test it as soon I can. Thank you for your help.
