### ISSUE TITLE
crash when trying for connect

### ISSUE THREAD

**Issue by oche0325** [epinna/weevely3#30]
Traceback (most recent call last):
  File "./weevely.py", line 98, in <module>
    main(arguments)
  File "./weevely.py", line 48, in main
    modules.load_modules(session)
  File "/home/oche/weevely/core/modules.py", line 24, in load_modules
    (module_group, module_name), fromlist=["*"]
  File "/home/oche/weevely/modules/shell/php.py", line 4, in <module>
    from core.channels.channel import Channel
  File "/home/oche/weevely/core/channels/channel.py", line 7, in <module>
    import socks
ImportError: No module named socks

and im using fedora 22.
Thanks.

**Comment by epinna** [comment]
Hello,

That's because you have to install PySocks library before to run weevely. 

Please follow the steps in the [Install and first run](https://github.com/epinna/weevely3/wiki/Install-and-first-run) wiki page.

Thanks
