### ISSUE TITLE
Readline missing from requirements.txt

### ISSUE THREAD

**Issue by benji1000** [epinna/weevely3#55]
Hello, thank you for this great tool!

One issue with the requirements: when doing `pip install -r requirements.txt`, I'm missing the readline library (or pyreadline on Windows).

```
Me@Computer MINGW64 /q/weevely3 (master)
$ pip install -r requirements.txt
Collecting prettytable (from -r requirements.txt (line 1))
  Downloading prettytable-0.7.2.zip
Collecting Mako (from -r requirements.txt (line 2))
  Downloading Mako-1.0.6.tar.gz (575kB)
Requirement already satisfied: PyYAML in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Collecting python-dateutil (from -r requirements.txt (line 4))
  Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)
Collecting PySocks (from -r requirements.txt (line 5))
  Downloading PySocks-1.6.5.tar.gz
Collecting MarkupSafe>=0.9.2 (from Mako->-r requirements.txt (line 2))
  Downloading MarkupSafe-0.23.tar.gz
Requirement already satisfied: six>=1.5 in c:\python27\lib\site-packages (from python-dateutil->-r requirements.txt (line 4))
Installing collected packages: prettytable, MarkupSafe, Mako, python-dateutil, PySocks
  Running setup.py install for prettytable: started
    Running setup.py install for prettytable: finished with status 'done'
  Running setup.py install for MarkupSafe: started
    Running setup.py install for MarkupSafe: finished with status 'done'
  Running setup.py install for Mako: started
    Running setup.py install for Mako: finished with status 'done'
  Running setup.py install for PySocks: started
    Running setup.py install for PySocks: finished with status 'done'
Successfully installed Mako-1.0.6 MarkupSafe-0.23 PySocks-1.6.5 prettytable-0.7.2 python-dateutil-2.6.0

Benjamin@C-3PO MINGW64 /q/weevely3 (master)
$ ./weevely.py generate MyP4ss! /q/web.php
Traceback (most recent call last):
  File "./weevely.py", line 2, in <module>
    from core.terminal import Terminal
  File "Q:\weevely3\core\terminal.py", line 9, in <module>
    import readline
ImportError: No module named readline
```

Could you add it to the requirements file? I don't know how to handle both Windows and Linux on this file though (maybe write one file for each OS, or a setup script)?

Thanks!

**Comment by epinna** [comment]
I only added `readline` for POSIX systems, if you want `pyreadline` on Windows you'll need to run the pip install procedure manually (see https://github.com/epinna/weevely3/wiki/Install-and-first-run ). Thanks for the contribution.
