### ISSUE TITLE
No module named 'strings'

### ISSUE THREAD

**Issue by Exant64** [epinna/weevely3#58]
I did everything that I have to do for the first run
Traceback (most recent call last):
  File "weevely.py", line 2, in <module>
    from core.terminal import Terminal
  File "C:\Python27\weevely3-master\core\terminal.py", line 6, in <module>
    from core.module import Status
  File "C:\Python27\weevely3-master\core\module.py", line 14, in <module>
    from core.vectorlist import VectorList
  File "C:\Python27\weevely3-master\core\vectorlist.py", line 15, in <module>
    from core.vectors import Os
  File "C:\Python27\weevely3-master\core\vectors.py", line 16, in <module>
    import utils
  File "C:\Python27\weevely3-master\utils\__init__.py", line 3, in <module>
    import strings
ImportError: No module named 'strings'

**Comment by epinna** [comment]
Do you have file `C:\Python27\weevely3-master\utils\strings.py`?
