### ISSUE TITLE
Errors when running the script

### ISSUE THREAD

**Issue by superbulka** [epinna/weevely3#63]
Hello. I downloaded the latest version of the script. I'm trying to run weevely, but I'm constantly getting errors. I could not find the answer myself. I ask for help.

```
C:\Python27>python --version
Python 2.7.13

```
```
C:\Python27\Scripts>pip-script.py install prettytable Mako PyYAML python-dateutil pyreadline PySocks --upgrade
Requirement already up-to-date: prettytable in c:\python27\lib\site-packages
Requirement already up-to-date: Mako in c:\python27\lib\site-packages
Requirement already up-to-date: PyYAML in c:\python27\lib\site-packages
Requirement already up-to-date: python-dateutil in c:\python27\lib\site-packages
Requirement already up-to-date: pyreadline in c:\python27\lib\site-packages
Requirement already up-to-date: PySocks in c:\python27\lib\site-packages
Requirement already up-to-date: MarkupSafe>=0.9.2 in c:\python27\lib\site-packages (from Mako)
Requirement already up-to-date: six>=1.5 in c:\python27\lib\site-packages (from python-dateutil)
```

```
Z:\weevely3>weevely.py generate 123 test2.php
Generated backdoor with password '123' in 'test2.php' of 1316 byte size.
```

```
Z:\weevely3>weevely.py http://mysite.com/test2.php 123
Traceback (most recent call last):
  File "Z:\weevely3\weevely.py", line 98, in <module>
    main(arguments)
  File "Z:\weevely3\weevely.py", line 51, in main
    Terminal(session).cmdloop()
  File "Z:\weevely3\core\terminal.py", line 149, in __init__
    default_shell = self.session.get('default_shell')
  File "C:\Python27\lib\site-packages\mako\template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 873, in _render_con
text
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\Python27\lib\site-packages\mako\runtime.py", line 899, in _exec_templ
ate
    callable_(context, *args, **kwargs)
  File "memory:0x3779358L", line 29, in render_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 9: ordinal
not in range(128)
```

**Comment by epinna** [comment]
Try deleting ".weevely" folder (note it starts with a dot) in your home folder and run it again (backup it if you have any session you want to save).

Do you still see the error message?

**Comment by superbulka** [comment]
Many thanks for the prompt reply! Yes, the error repeats one to one. I do not have any saved sessions yet, this is the first installation of your script. Previously, I used the old version of the product (not version 3) and I decided to upgrade

**Comment by epinna** [comment]
That's weird... Not sure how to reproduce it, but I'll investigate.

**Comment by superbulka** [comment]
I apologize for not having written at once. Problem solved. In order for everything to work correctly on Windows, you don't need to use pip-script.py script. It is necessary to download each module separately from pypi.python.org + a win_inet_pton module is needed.
