### ISSUE TITLE
Some Errors!

### ISSUE THREAD

**Issue by xday3** [epinna/weevely3#65]
After uploaded the shell on the website...and running any command...its show me following errors...can you help me?

[+] weevely 3.4

[+] Target:     xxxxxxxx.com
[+] Session:    /root/.weevely/sessions/xxxxxxxx.com/se_0.session

[+] Browse the filesystem or execute commands starts the connection
[+] to the target. Type :help for more information.

weevely> ls
Traceback (most recent call last):
  File "weevely.py", line 98, in <module>
    main(arguments)
  File "weevely.py", line 51, in main
    Terminal(session).cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 141, in cmdloop
    line = self.precmd(line)
  File "/var/www/py/weevely3/core/terminal.py", line 196, in precmd
    self.session['shell_sh']['status'] = modules.loaded['shell_sh'].setup()
  File "/var/www/py/weevely3/modules/shell/sh.py", line 99, in setup
    condition = lambda result: (
  File "/var/www/py/weevely3/core/vectorlist.py", line 80, in find_first_result
    result = vector.run(format_args)
  File "/var/www/py/weevely3/core/vectors.py", line 121, in run
    result = modules.loaded[self.module].run_argv(formatted)
  File "/var/www/py/weevely3/core/module.py", line 173, in run_argv
    self.session[self.name]['status'] = self.setup()
  File "/var/www/py/weevely3/modules/shell/php.py", line 67, in setup
    status = self._check_interpreter(channel)
  File "/var/www/py/weevely3/modules/shell/php.py", line 39, in _check_interpreter
    response, code, error = channel.send(command)
  File "/var/www/py/weevely3/core/channels/channel.py", line 112, in send
    self._additional_handlers()
  File "/var/www/py/weevely3/core/channels/channel.py", line 93, in _additional_handlers
    ctx = ssl.create_default_context()
AttributeError: 'module' object has no attribute 'create_default_context'

**Comment by epinna** [comment]
You're using an old python version. Update your python version, see issue #60 .
