### ISSUE TITLE
bunch or errors

### ISSUE THREAD

**Issue by tehseensagar** [epinna/weevely3#76]
Hello I just setup weevely on my ubuntu box ,

./weevely.py generate my-pass class.php
uploaded that file on my target machine and run it via browser
then ./weevely http://x.x.x.x/class.php my-pass

[+] weevely 3.5

[+] Target:     target.com
[+] Session:    /root/.weevely/sessions/target.com/class_0.session

[+] Browse the filesystem or execute commands starts the connection
[+] to the target. Type :help for more information.

when I do ls I got bunch of errors dont know what is wrong.

`Traceback (most recent call last):
  File "weevely.py", line 98, in <module>
    main(arguments)
  File "weevely.py", line 51, in main
    Terminal(session).cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 141, in cmdloop
    line = self.precmd(line)
  File "/opt/weevely3-master/core/terminal.py", line 196, in precmd
    self.session['shell_sh']['status'] = modules.loaded['shell_sh'].setup()
  File "/opt/weevely3-master/modules/shell/sh.py", line 99, in setup
    condition = lambda result: (
  File "/opt/weevely3-master/core/vectorlist.py", line 80, in find_first_result
    result = vector.run(format_args)
  File "/opt/weevely3-master/core/vectors.py", line 121, in run
    result = modules.loaded[self.module].run_argv(formatted)
  File "/opt/weevely3-master/core/module.py", line 173, in run_argv
    self.session[self.name]['status'] = self.setup()
  File "/opt/weevely3-master/modules/shell/php.py", line 67, in setup
    status = self._check_interpreter(channel)
  File "/opt/weevely3-master/modules/shell/php.py", line 39, in _check_interpreter
    response, code, error = channel.send(command)
  File "/opt/weevely3-master/core/channels/channel.py", line 112, in send
    self._additional_handlers()
  File "/opt/weevely3-master/core/channels/channel.py", line 93, in _additional_handlers
    ctx = ssl.create_default_context()
AttributeError: 'module' object has no attribute 'create_default_context'
`

Looking forward to your kind response.

Regards

**Comment by epinna** [comment]
You're using an old python version. Update your python version, see issue #60 .
