### ISSUE TITLE
=((((( only todAY

### ISSUE THREAD

**Issue by mayday77** [epinna/weevely3#78]
Traceback (most recent call last):
  File "weevely.py", line 98, in <module>
    main(arguments)
  File "weevely.py", line 38, in main
    password = arguments.password
  File "/jOSEPH/Downloads/weevely3/core/sessions.py", line 223, in __init__
    saved_url = sessiondb.get('url')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by mayday77** [comment]
Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux
