### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Phexcom** [epinna/weevely3#80]
Traceback (most recent call last):
  File "./weevely.py", line 98, in <module>
    main(arguments)
  File "./weevely.py", line 38, in main
    password = arguments.password
  File "/usr/share/weevely/core/sessions.py", line 223, in __init__
    saved_url = sessiondb.get('url')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by epinna** [comment]
Same as #47, see there.
