### ISSUE TITLE
Cannot run weevely3

### ISSUE THREAD

**Issue by wirehack7** [epinna/weevely3#83]
I'm getting this error when trying to connect to an agent:

```
Traceback (most recent call last):
  File "./weevely.py", line 99, in <module>
    main(arguments)
  File "./weevely.py", line 39, in main
    password = arguments.password
  File "/root/tools/weevely3/core/sessions.py", line 225, in __init__
    saved_url = sessiondb.get('url')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by epinna** [comment]
Could you please pull and try now?

**Comment by wirehack7** [comment]
Works now. 👍
