### ISSUE TITLE
Missing Module

### ISSUE THREAD

**Issue by Hultonus** [epinna/weevely3#96]
Hey, I have an issue. Whenever I try to launch weevely.py i get this:

```
Traceback (most recent call last):
  File "./weevely.py", line 2, in <module>
    from core.terminal import Terminal
  File "/root/weevely3/core/terminal.py", line 6, in <module>
    from core.module import Status
  File "/root/weevely3/core/module.py", line 14, in <module>
    from core.vectorlist import VectorList
  File "/root/weevely3/core/vectorlist.py", line 15, in <module>
    from core.vectors import Os
  File "/root/weevely3/core/vectors.py", line 11, in <module>
    from mako.template import Template
ImportError: No module named mako.template

```

Any idea how to fix that?

**Comment by epinna** [comment]
Hello, you miss a Python module. Please follow the [Install](https://github.com/epinna/weevely3/wiki/Install) wiki page to see how to install the requirements.
